export const ALARM_CONTENT_TYPES = {
  POST_SCRAP: 'POST_SCRAP',
  POST_COMMENT: 'POST_COMMENT',
  POST_REACTION: 'POST_REACTION',
  COMMENT_SCRAP: 'COMMENT_SCRAP',
  COMMENT_REPLY: 'COMMENT_REPLY',
  COMMENT_REACTION: 'COMMENT_REACTION',
};
